name: Create Gateway API plugin release
on:
  push:
    tags:
      - "release-v[0-9]+.[0-9]+.[0-9]+-?[a-zA-Z0-9]*"

jobs:
  release-creation:
    name: Automatic release creation triggered on ${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      # The name of the tag as supplied by the GitHub event
      SOURCE_TAG: ${{ github.ref }}
      # Whether to create release
      DRY_RUN: false
      # Whether a draft release should be created, instead of public one
      DRAFT_RELEASE: false
      # Name of the GitHub user for Git config
      GIT_USERNAME: PhilippPlotnikov
      # E-Mail of the GitHub user for Git config
      GIT_EMAIL: philipp.plotnikov@codefresh.io
    steps: 
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          draft: ${{ env.DRAFT_RELEASE }}
          prerelease: ${{ env.PRE_RELEASE }}
          body: ${{ steps.release-notes.outputs.content }}

      - name: Upload gateway-api-plugin-linux-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gateway-api-plugin-linux-amd64
          asset_name: gateway-api-plugin-linux-amd64
          asset_content_type: application/octet-stream
        if: ${{ env.DRY_RUN != 'true' }}

      - name: Upload gateway-api-plugin-linux-arm64 binary to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gateway-api-plugin-linux-arm64
          asset_name: gateway-api-plugin-linux-arm64
          asset_content_type: application/octet-stream
        if: ${{ env.DRY_RUN != 'true' }}

      - name: Upload gateway-api-plugin-darwin-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gateway-api-plugin-darwin-amd64
          asset_name: gateway-api-plugin-darwin-amd64
          asset_content_type: application/octet-stream
        if: ${{ env.DRY_RUN != 'true' }}

      - name: Upload gateway-api-plugin-darwin-arm64 binary to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gateway-api-plugin-darwin-arm64
          asset_name: gateway-api-plugin-darwin-arm64
          asset_content_type: application/octet-stream
        if: ${{ env.DRY_RUN != 'true' }}

      - name: Upload gateway-api-plugin-windows-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gateway-api-plugin-windows-amd64.exe
          asset_name: gateway-api-plugin-windows-amd64.exe
          asset_content_type: application/octet-stream
        if: ${{ env.DRY_RUN != 'true' }}

